/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    node_recov_db.c
 *
 * @brief
 *		node_recov_db.c - This file contains the functions to record a node
 *		data structure to database and to recover it from database.
 *
 * Included functions are:
 *	node_save_db()
 *	svr_to_db_node()
 *	node_delete_db()
 */


#include <pbs_config.h>   /* the master config generated by configure */

#include <stdio.h>
#include <sys/types.h>

#include "pbs_ifl.h"
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#include <unistd.h>
#include "server_limits.h"
#include "list_link.h"
#include "attribute.h"

#include "log.h"
#include "attribute.h"
#include "list_link.h"
#include "server_limits.h"
#include "credential.h"
#include "libpbs.h"
#include "batch_request.h"
#include "pbs_nodes.h"
#include "job.h"
#include "resource.h"
#include "reservation.h"
#include "queue.h"
#include "svrfunc.h"
#include <memory.h>
#include "libutil.h"
#include "pbs_db.h"

#ifdef NAS /* localmod 005 */
/* External Functions Called */
extern int recov_attr_db(pbs_db_conn_t *conn,
	void *parent,
	pbs_db_attr_info_t *p_attr_info,
	struct attribute_def *padef,
	struct attribute *pattr,
	int limit,
	int unknown);
extern int recov_attr_db_raw(pbs_db_conn_t *conn,
	pbs_db_attr_info_t *p_attr_info,
	pbs_list_head *phead);
#endif /* localmod 005 */

/**
 * @brief
 *		Load a server node object from a database node object
 *
 * @param[out]	pnode - Address of the node in the server
 * @param[in]	pdbnd - Address of the database node object
 *
 * @return	Error code
 * @retval   0 - Success
 * @retval  -1 - Failure
 *
 */
static int
db_to_svr_node(struct pbsnode *pnode, pbs_db_node_info_t *pdbnd)
{
	if (pnode->nd_name == NULL && pdbnd->nd_name && pdbnd->nd_name[0] != 0) {
		pnode->nd_name = strdup(pdbnd->nd_name);
		if (pnode->nd_name == NULL)
			return -1;
	}


	if (pdbnd->nd_hostname && pdbnd->nd_hostname[0]!=0) {
		pnode->nd_hostname = strdup(pdbnd->nd_hostname);
		if (pnode->nd_hostname == NULL)
			return -1;
	}
	else
		pnode->nd_hostname = NULL;

	pnode->nd_ntype = pdbnd->nd_ntype;
	pnode->nd_state = pdbnd->nd_state;
	if (pnode->nd_pque)
		strcpy(pnode->nd_pque->qu_qs.qu_name, pdbnd->nd_pque);

	if ((decode_attr_db(pnode, &pdbnd->attr_list, node_attr_def,
		pnode->nd_attr, (int) ND_ATR_LAST, 0)) != 0)
		return -1;

	return 0;
}

/**
 * @brief
 *		Recover a node from the database
 *
 * @param[in]	nd_name	- node name
 *
 * @return	The recovered node structure
 * @retval	NULL - Failure
 * @retval	!NULL - Success - address of recovered node returned
 */
struct pbsnode *
node_recov_db(char *nd_name)
{
	pbs_db_obj_info_t obj;
	pbs_db_conn_t *conn = (pbs_db_conn_t *) svr_db_conn;
	pbs_db_node_info_t dbnode = {{0}};
	int rc = 0;
	struct pbsnode *pnode = NULL;

	strcpy(dbnode.nd_name, nd_name);
	obj.pbs_db_obj_type = PBS_DB_NODE;
	obj.pbs_db_un.pbs_db_node = &dbnode;

	rc = pbs_db_load_obj(conn, &obj);

	if (rc == 0) {
		if ((pnode = malloc(sizeof(struct pbsnode))) != NULL) {
			initialize_pbsnode(pnode, strdup(nd_name), NTYPE_PBS);
		} else {
			log_err(-1, __func__, "node_alloc failed");
			return NULL;
		}
		rc = db_to_svr_node(pnode, &dbnode);
	}
	
	pbs_db_reset_obj(&obj);

	if (rc != 0) {
		snprintf(log_buffer, LOG_BUF_SIZE,  "error on recovering node: %s", nd_name);
		log_err(-1, __func__, log_buffer);
		if (pnode) {
			free(pnode); /* free if we allocated here */
			pnode = NULL; /* so we return NULL */
		}
	}
	return pnode;
}

/**
 * @brief
 *		Load a database node object from a server node object
 *
 * @param[in]	pnode - Address of the node in the server
 * @param[out]	pdbnd - Address of the database node object
 *
 * @return 0    Success
 * @return !=0  Failure
 */
static int
svr_to_db_node(struct pbsnode *pnode, pbs_db_node_info_t *pdbnd)
{
	if (pnode->nd_name)
		strcpy(pdbnd->nd_name, pnode->nd_name);
	else
		pdbnd->nd_name[0]=0;

	/* node_index is used to sort vnodes upon recovery.
	 * For Cray multi-MoM'd vnodes, we ensure that natural vnodes come
	 * before the vnodes that it manages by introducing offsetting all
	 * non-natural vnodes indices to come after natural vnodes.
	 */
	pdbnd->nd_index = (pnode->nd_nummoms * svr_totnodes) + pnode->nd_index;

	if (pnode->nd_hostname)
		strcpy(pdbnd->nd_hostname, pnode->nd_hostname);
	else
		pdbnd->nd_hostname[0]=0;

	if (pnode->nd_moms && pnode->nd_moms[0])
		pdbnd->mom_modtime = pnode->nd_moms[0]->mi_modtime;
	else
		pdbnd->mom_modtime = 0;

	pdbnd->nd_ntype = pnode->nd_ntype;
	pdbnd->nd_state = pnode->nd_state;
	if (pnode->nd_pque)
		strcpy(pdbnd->nd_pque, pnode->nd_pque->qu_qs.qu_name);
	else
		pdbnd->nd_pque[0]=0;

	if ((encode_attr_db(node_attr_def,
		pnode->nd_attr,
		(int)ND_ATR_LAST, &pdbnd->attr_list, 0)) != 0)
		return -1;

	return 0;
}

/**
 * @brief
 *	Save a node to the database. When we save a node to the database, delete
 *	the old node information and write the node afresh. This ensures that
 *	any deleted attributes of the node are removed, and only the new ones are
 *	updated to the database.
 *
 * @param[in]	pnode - Pointer to the node to save
 * @param[in]	mode:
 *		NODE_SAVE_FULL - Full update along with attributes
 *		NODE_SAVE_QUICK - Quick update without attributes
 *		NODE_SAVE_NEW	- New node insert into database
 *		NODE_SAVE_QUICK_STATE - Quick update, along with state attrib
 *
 * @return      Error code
 * @retval	0 - Success
 * @retval	-1 - Failure
 *
 */
int
node_save_db(struct pbsnode *pnode)
{
	pbs_db_node_info_t dbnode;
	pbs_db_obj_info_t obj;
	pbs_db_conn_t *conn = (pbs_db_conn_t *) svr_db_conn;

	obj.pbs_db_obj_type = PBS_DB_NODE;
	obj.pbs_db_un.pbs_db_node = &dbnode;

	svr_to_db_node(pnode, &dbnode);

	if (pbs_db_save_obj(conn, &obj, PBS_UPDATE_DB_FULL) != 0) {
		if (pbs_db_save_obj(conn, &obj, PBS_INSERT_DB) != 0) {
			goto db_err;
		}
	}

	pbs_db_reset_obj(&obj);

	return (0);
db_err:
	pbs_db_reset_obj(&obj);
	strcpy(log_buffer, "node_save failed ");
	if (conn->conn_db_err != NULL)
		strncat(log_buffer, conn->conn_db_err, LOG_BUF_SIZE - strlen(log_buffer) - 1);
	log_err(-1, "node_save_db", log_buffer);
	panic_stop_db(log_buffer);
	return (-1);
}

/**
 * @brief
 *		Refresh a node
 *
 * @param[in]	dbnode	- databse node structure
 *
 * @return	The recovered node structure
 * @retval	NULL - Failure
 * @retval	!NULL - Success - address of recovered node returned
 */
struct pbsnode *
refresh_node(pbs_db_node_info_t *dbnode)
{
	pbs_node *pnode = NULL;
	struct pbsnode *pnd = NULL;

	pnode = find_nodefromtree(dbnode->nd_name);
	if (pnode == NULL) {
		if ((pnd = malloc(sizeof(struct pbsnode)))) {
			pnode = pnd;
			initialize_pbsnode(pnode, strdup(dbnode->nd_name), NTYPE_PBS);
		} else {
			log_err(-1, __func__, "node_alloc failed");
			return NULL;
		}
		db_to_svr_node(pnode, dbnode);
		/* We dont need resc assn values */
		reset_resc(&pnode->nd_attr[(int)ND_ATR_ResourceAssn], ATTR_rescassn);
		if (update_node_cache(pnode, TREE_OP_ADD) != 0)
			return NULL;
	}
	return pnode;
}


/**
 * @brief
 *	Delete a node from the database
 *
 * @param[in]	pnode - Pointer to the node to delete
 *
 * @return      Error code
 * @retval	0 - Success
 * @retval	-1 - Failure
 *
 */
int
node_delete_db(struct pbsnode *pnode)
{
	pbs_db_node_info_t dbnode;
	pbs_db_obj_info_t obj;
	pbs_db_conn_t *conn = (pbs_db_conn_t *) svr_db_conn;

	snprintf(dbnode.nd_name, sizeof(dbnode.nd_name), "%s", pnode->nd_name);
	obj.pbs_db_obj_type = PBS_DB_NODE;
	obj.pbs_db_un.pbs_db_node = &dbnode;

	if (pbs_db_delete_obj(conn, &obj) == -1)
		return (-1);
	else
		return (0);	/* "success" or "success but rows deleted" */
}
