/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

/** @file	int_status.c
 * @brief
 * The function that underlies all the status requests
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <string.h>
#include <stdio.h>
#include "libpbs.h"
#include "pbs_ecl.h"

/**
 * @brief
 * 	get_available_conn:
 *	get one of the available connection from multisvr sd
 *
 * @param[in] svr_connections - pointer to array of server connections
 *
 * @return int
 * @retval -1: error
 * @retval != -1 fd corresponding to the connection
 */
int
get_available_conn(svr_conn_t *svr_connections)
{
	int i;

	for (i = 0; i < get_num_servers(); i++)
		if (svr_connections[i].state == SVR_CONN_STATE_UP)
			return svr_connections[i].sd;

	return -1;
}

/**
 * @brief
 * random_srv_conn:
 *	get random server sd - It will choose a random sd from available no of servers.
 * @param[in] svr_connections - pointer to array of server connections
 *
 * @return int
 * @retval -1: error
 * @retval != -1: fd corresponding to the connection
 */
int
random_srv_conn(svr_conn_t *svr_connections)
{
	int ind = 0;

	ind =  rand_num() % get_num_servers();

	if (svr_connections[ind].state == SVR_CONN_STATE_UP)
		return svr_connections[ind].sd;

	return get_available_conn(svr_connections);
}

/**
 * @brief
 *	-wrapper function for PBSD_status_put which sends
 *	status batch request
 *
 * @param[in] c - socket descriptor
 * @param[in] function - request type
 * @param[in] id - object id
 * @param[in] attrib - pointer to attribute list
 * @param[in] extend - extention string for req encode
 *
 * @return	structure handle
 * @retval 	pointer to batch status on SUCCESS
 * @retval 	NULL on failure
 *
 */
struct batch_status *
PBSD_status(int c, int function, char *objid, struct attrl *attrib, char *extend)
{
	int rc;
	struct batch_status *PBSD_status_get(int c);

	/* send the status request */

	if (objid == NULL)
		objid = "";	/* set to null string for encoding */

	rc = PBSD_status_put(c, function, objid, attrib, extend, PROT_TCP, NULL);
	if (rc) {
		return NULL;
	}

	/* get the status reply */
	return (PBSD_status_get(c));
}

/**
 * @brief
 *	Returns pointer to status record
 *
 * @param[in] c - index into connection table
 *
 * @return returns a pointer to a batch_status structure
 * @retval pointer to batch status on SUCCESS
 * @retval NULL on failure
 */
struct batch_status *
PBSD_status_get(int c)
{
	struct batch_status *rbsp = NULL;
	struct batch_reply  *reply;

	/* read reply from stream into presentation element */

	reply = PBSD_rdrpy(c);
	if (reply == NULL) {
		pbs_errno = PBSE_PROTOCOL;
	} else if (reply->brp_choice != BATCH_REPLY_CHOICE_NULL  &&
		reply->brp_choice != BATCH_REPLY_CHOICE_Text &&
		reply->brp_choice != BATCH_REPLY_CHOICE_Status) {
		pbs_errno = PBSE_PROTOCOL;
	} else if (get_conn_errno(c) == 0) {
		rbsp = reply->brp_un.brp_statc;
		reply->brp_un.brp_statc = NULL;
	}
	PBSD_FreeReply(reply);
	return rbsp;
}

/**
 * @brief	wrapper function for PBSD_status, aggregates output from all servers.
 *
 * @param[in] c - communication handle
 * @param[in] id - job id
 * @param[in] attrib - pointer to attribute list
 * @param[in] extend - extend string for req
 * @param[in] cmd - command
 *
 * @return	structure handle
 * @retval	pointer to batch_status struct		success
 * @retval	NULL					error
 *
 */
struct batch_status *
PBSD_status_aggregate(int c, int function, char *id, struct attrl *attrib, char *extend, int parent_object)
{
	int i;
	int rc = 0;
	struct batch_status *ret = NULL;
	struct batch_status *next = NULL;
	struct batch_status *cur = NULL;
	svr_conn_t *svr_connections = get_conn_servers();
	int num_svrs = get_num_servers();
	int *failed_conn;

	if (!svr_connections)
		return NULL;

	failed_conn = calloc(num_svrs, sizeof(int));

	/* initialize the thread context data, if not already initialized */
	if (pbs_client_thread_init_thread_context() != 0)
		return NULL;

	if (pbs_client_thread_lock_connection(c) != 0)
		return NULL;

	if (id == NULL)
		id = "";

	/* Send stat request to all available servers */
	for (i = 0; i < num_svrs; i++) {
		if (svr_connections[i].state != SVR_CONN_STATE_UP)
			continue;

		if (PBSD_status_put(svr_connections[i].sd, function, id, attrib, extend, PROT_TCP, NULL) != 0) {
			failed_conn[i] = 1;
			if (pbs_client_thread_unlock_connection(c) != 0)
				return NULL;
			continue;
		}
	}

	/* Aggregate output */
	for (i = 0; i < num_svrs; i++) {
		if (svr_connections[i].state != SVR_CONN_STATE_UP)
			continue;

		if (failed_conn[i])
			continue;

		if ((next = PBSD_status_get(svr_connections[i].sd))) {
			if (!ret)
				ret = next;
			else
				cur->next = next;
			cur = next;
		}
	}

	/* unlock the thread lock and update the thread context data */
	if (pbs_client_thread_unlock_connection(c) != 0)
		return NULL;

	if (rc)
		pbs_errno = rc;

	free(failed_conn);
	return ret;
}

/**
 * @brief
 *	wrapper function for PBSD_status
 *	gets status randomly from one of the configured server.
 *
 * @param[in] c - communication handle
 * @param[in] id - job id
 * @param[in] attrib - pointer to attribute list
 * @param[in] extend - extend string for req
 * @param[in] cmd - command
 *
 * @return	structure handle
 * @retval	pointer to batch_status struct		success
 * @retval	NULL					error
 *
 */
struct batch_status *
PBSD_status_random(int c, int function, char *id, struct attrl *attrib, char *extend, int parent_object)
{
	struct batch_status *ret = NULL;
	svr_conn_t *svr_connections = get_conn_servers();

	if (!svr_connections)
		return NULL;

	if ((c = random_srv_conn(svr_connections)) < 0)
		return NULL;

	/* initialize the thread context data, if not already initialized */
	if (pbs_client_thread_init_thread_context() != 0)
		return NULL;

	/* first verify the attributes, if verification is enabled */
	if ((pbs_verify_attributes(c, function, parent_object, MGR_CMD_NONE, (struct attropl *) attrib)))
		return NULL;

	if (pbs_client_thread_lock_connection(c) != 0)
		return NULL;

	ret = PBSD_status(c, function, id, attrib, extend);

	/* unlock the thread lock and update the thread context data */
	if (pbs_client_thread_unlock_connection(c) != 0)
		return NULL;

	return ret;
}

