# base image for building pbspro
FROM centos:7
# install dependencies for building
RUN yum install -y \
    expat-devel \
    gcc \
    git \
    hwloc-devel \
    libedit-devel \
    libical-devel \
    libtool \
    libX11-devel \
    libXext \
    libXft \
    libXt-devel \
    make \
    ncurses-devel \
    openssl-devel \
    perl \
    postgresql-contrib \
    postgresql-devel \
    python3 \
    python3-devel \
    rpm-build \
    swig \
    tcl-devel \
    tk-devel
