#!/bin/bash -x

/workspace/etc/install-system-packages 2>&1 | tee -a /logs/build-$(hostname -s)

# set environment var file
touch /.env-file
set >/.env-file

capsh --print | grep -Eq '*cap_sys_admin*'
if [ $? -eq 0 ]; then
	if [ -x "/usr/lib/systemd/systemd" ]; then
		exec /usr/lib/systemd/systemd --system
	elif [ -x "/lib/systemd/systemd" ]; then
		exec /lib/systemd/systemd --system
	elif [ -x "/usr/sbin/init" ]; then
		exec /usr/sbin/init
	elif [ -x "/sbin/init" ]; then
		exec /sbin/init
	else
		echo "Couldn't start container in systemd mode, starting in default mode"
	fi
fi
